version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data/mongodb:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    expose:
      - 9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    expose:
      - 5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379

  app:
    container_name: datasynchub-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - redis
      - elasticsearch
      - kibana
